[project]
name = "capacities-ml-fin"
version = "0.1.0"
description = "Capacities, Choquet machine learning, and non-additive financial risk measures."
authors = [
    {name = "ikercb2000", email = "ikercb2000@gmail.com"}
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12,<3.15"
keywords = [
    "capacities",
    "choquet-integral",
    "machine-learning",
    "risk-measures",
    "financial-risk",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy (>=2.0.0,<2.5.0)",
    "pandas (>=2.2.0,<3.0.0)",
    "scipy (>=1.18.0,<2.0.0)",
    "cvxpy (>=1.9.2,<2.0.0)",
    "scikit-learn (>=1.6.0,<1.8.0)",
    "sktime (>=1.1.0,<2.0.0)",
    "statsmodels (>=0.14.6,<0.15.0)",
    "pymoo (>=0.6.2,<0.7.0)",
    "dotenv (>=0.9.9,<0.10.0)",
]

[project.urls]
Homepage = "https://github.com/ikercb2000/capacities_ml_fin"
Repository = "https://github.com/ikercb2000/capacities_ml_fin"
Issues = "https://github.com/ikercb2000/capacities_ml_fin/issues"

[tool.poetry]
packages = [{include = "capacities_ml_fin", from = "src"}]

[dependency-groups]
test = [
    "polars (>=1.43.1,<2.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
]
dev = [
    {include-group = "test"},
    "matplotlib (>=3.11.1,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "commitizen (>=4.17.0,<5.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)",
    "twine (>=6.2.0,<7.0.0)",
]
docs = [
    "mkdocs-material (>=9.7.7,<10.0.0)",
    "mkdocstrings-python (>=2.0.5,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
