# imports
from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass
import numpy as np
from numpy.typing import NDArray

# modules
from capacities_ml_fin.ml.optimization.capacity_constraints import (
    CapacityParameterization,
    capacity_value_constraints,
    mobius_capacity_constraints,
    pairwise_interaction_constraints,
)
from capacities_ml_fin.ml.optimization.constraints import ConstraintBundle
from capacities_ml_fin.ml.optimization.enums import CapacityShape

# sparsity aliases
FloatArray = NDArray[np.float64]

# sparsity compilation
@dataclass(frozen=True, slots=True)
class SparsityCompilation:
    """Numerical parameterization generated by a sparsity specification."""

    bundle: CapacityParameterization
    initial_parameters: FloatArray


# capacity sparsity base class
class CapacitySparsity(ABC):
    """Generate parameters and constraints for a family of capacities."""

    @abstractmethod
    def compile(self, n_elements: int) -> SparsityCompilation:
        """Build the parameterization for a variable universe."""


# full capacity sparsity
@dataclass(frozen=True, slots=True)
class FullCapacity(CapacitySparsity):
    """Keep every capacity value as an optimization parameter."""

    def compile(self, n_elements: int) -> SparsityCompilation:
        parameterization = capacity_value_constraints(n_elements)
        initial = np.asarray(
            [mask.bit_count() / n_elements for mask in parameterization.parameter_masks],
            dtype=float,
        )
        return SparsityCompilation(
            bundle=parameterization,
            initial_parameters=initial,
        )


# k-additivity sparsity
@dataclass(frozen=True, slots=True)
class KAdditivity(CapacitySparsity):
    """Restrict a capacity to non-zero Mobius terms up to ``order``."""
    order: int
    shape: CapacityShape = CapacityShape.GENERAL

    def __post_init__(self) -> None:
        if not isinstance(self.shape, CapacityShape):
            raise TypeError("shape must be a CapacityShape enum member.")

    def compile(self, n_elements: int) -> SparsityCompilation:
        bundle = mobius_capacity_constraints(
            n_elements,
            self.order,
            shape=self.shape,
        )

        # Equal singleton terms provide a normalized, monotone starting point.
        initial = np.zeros(bundle.n_parameters, dtype=float)
        singleton_positions = [
            position
            for position, mask in enumerate(bundle.parameter_masks)
            if mask.bit_count() == 1
        ]
        initial[singleton_positions] = 1.0 / n_elements
        return SparsityCompilation(bundle=bundle, initial_parameters=initial)


# pairwise interaction sparsity
@dataclass(frozen=True, slots=True)
class PairwiseInteractionSparsity(CapacitySparsity):
    """Keep selected pairwise interaction indices fixed to target values."""

    order: int
    pairs: tuple[tuple[int, int], ...] | None = None
    target: float = 0.0
    shape: CapacityShape = CapacityShape.GENERAL

    def __post_init__(self) -> None:
        if not isinstance(self.shape, CapacityShape):
            raise TypeError("shape must be a CapacityShape enum member.")
        if self.order < 2:
            raise ValueError("order must be at least 2 for pairwise interactions.")

    def compile(self, n_elements: int) -> SparsityCompilation:
        bundle = mobius_capacity_constraints(
            n_elements,
            self.order,
            shape=self.shape,
        )
        interaction_system = pairwise_interaction_constraints(
            n_elements,
            self.order,
            pairs=self.pairs,
            lower=self.target,
            upper=self.target,
        )
        bundle = type(bundle)(
            constraints=ConstraintBundle(
                bounds=bundle.constraints.bounds,
                linear_constraints=bundle.constraints.linear_constraints
                + (interaction_system,),
                nonlinear_constraints=bundle.constraints.nonlinear_constraints,
            ),
            parameter_masks=bundle.parameter_masks,
            representation=bundle.representation,
            n_features=bundle.n_features,
            max_order=bundle.max_order,
        )
        initial = np.zeros(bundle.n_parameters, dtype=float)
        singleton_positions = [
            position
            for position, mask in enumerate(bundle.parameter_masks)
            if mask.bit_count() == 1
        ]
        initial[singleton_positions] = 1.0 / n_elements
        return SparsityCompilation(bundle=bundle, initial_parameters=initial)
