# imports
from pathlib import Path
import sys

import numpy as np
import polars as pl


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# modules
from capacities_ml.capacities import Capacity, VariableUniverse
from capacities_ml.capacities.utils import subset_decoding
from capacities_ml.integrals.batch_integrals import batch_choquet_integral
from capacities_ml.mobius import inverse_mobius_transform
from capacities_ml.optimization import KAdditivity, Optimizer, Problem, Solver


# synthetic data
def build_synthetic_data(
    n_observations: int = 50,
    seed: int = 7,
) -> tuple[pl.DataFrame, np.ndarray, dict[int, float]]:
    """Create observations and a noisy target generated by a known capacity."""
    rng = np.random.default_rng(seed)
    features = rng.uniform(0.0, 1.0, size=(n_observations, 3))

    true_values = {
        0b000: 0.0,
        0b001: 0.20,
        0b010: 0.30,
        0b100: 0.10,
        0b011: 0.60,
        0b101: 0.45,
        0b110: 0.55,
        0b111: 1.00,
    }
    clean_target = choquet_values(features, true_values)
    target = clean_target + rng.normal(0.0, 0.02, size=n_observations)

    data = pl.DataFrame(
        {
            "price": features[:, 0],
            "quality": features[:, 1],
            "reliability": features[:, 2],
            "target": target,
        }
    )
    return data, target, true_values


# direct choquet evaluation for numerical optimization
def choquet_values(X: np.ndarray, capacity_values: dict[int, float]) -> np.ndarray:
    """Evaluate Choquet integrals from values indexed by coalition masks."""
    order = np.argsort(X, axis=1, kind="stable")
    sorted_X = np.take_along_axis(X, order, axis=1)
    previous = np.concatenate(
        [
            np.zeros((X.shape[0], 1), dtype=float),
            sorted_X[:, :-1],
        ],
        axis=1,
    )

    sorted_bits = 1 << order
    masks = np.flip(
        np.cumsum(np.flip(sorted_bits, axis=1), axis=1),
        axis=1,
    )
    values = np.zeros(1 << X.shape[1], dtype=float)
    for mask, value in capacity_values.items():
        values[mask] = value

    return np.einsum("ij,ij->i", sorted_X - previous, values[masks])


def capacity_values_from_mobius(
    parameters: np.ndarray,
    parameter_masks: tuple[int, ...],
    n_vars: int,
) -> dict[int, float]:
    """Build all capacity values from the active Mobius coefficients."""
    coefficients = dict(zip(parameter_masks, parameters))
    values = {0: 0.0}
    for mask in range(1, 1 << n_vars):
        submask = mask
        values[mask] = 0.0
        while True:
            values[mask] += coefficients.get(submask, 0.0)
            if submask == 0:
                break
            submask = (submask - 1) & mask
    return values


# main optimization example
def main() -> None:
    data, target, true_values = build_synthetic_data()
    universe = VariableUniverse(
        var_names=("price", "quality", "reliability")
    )

    feature_columns = ["price", "quality", "reliability"]
    X = data.select(feature_columns).to_numpy()

    sparsity = KAdditivity(order=2)
    parameter_masks = sparsity.compile(universe.n_vars).bundle.parameter_masks

    # The objective receives the active Mobius coefficients.
    def objective(parameters: np.ndarray) -> float:
        predictions = choquet_values(
            X,
            capacity_values_from_mobius(
                parameters,
                parameter_masks,
                universe.n_vars,
            ),
        )
        return float(np.mean((predictions - target) ** 2))

    problem = Problem.from_capacity(
        universe=universe,
        objective=objective,
        sparsity=sparsity,
        name="synthetic_choquet_capacity_fit",
    )

    print("Synthetic capacity optimization")
    print(f"Observations: {data.height}")
    print(f"Data columns: {data.columns}")
    print("First three observations:")
    print(data.head(3).write_csv())
    initial = problem.initial_parameters
    print(f"Active parameters (Mobius terms): {problem.n_parameters}")
    print(f"Initial objective: {problem.objective(initial):.6f}")

    optimizer = Optimizer(
        solver=Solver.SCIPY,
        options={"maxiter": 500, "ftol": 1e-12},
    )
    result = optimizer.solve(problem)
    mobius = problem.decode_result(result)
    capacity = inverse_mobius_transform(mobius)

    predictions = batch_choquet_integral(X, capacity)
    fitted_mse = float(np.mean((predictions - target) ** 2))
    true_capacity = Capacity(
        universe=universe,
        values={
            subset_decoding(mask, universe.n_vars): value
            for mask, value in true_values.items()
            if mask != 0
        },
    )

    print()
    print("Optimization result")
    print(f"Solver: {result.solver_name}")
    print(f"Success: {result.success}")
    print(f"Status: {result.status}")
    print(f"Message: {result.message}")
    print(f"Objective reported by solver: {result.objective_value:.6f}")
    print(f"Objective recomputed from Capacity: {fitted_mse:.6f}")
    print()
    print("True capacity values")
    print(true_capacity.to_named_dict())
    print()
    print("Fitted capacity values")
    print(capacity.to_named_dict())


if __name__ == "__main__":
    main()
